version: "3.2"

services:
  financial-transaction-listener:
    image: financial-transaction-listener
    build:
      context: .
      dockerfile: FinancialTransactionListener/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
     - ENVIRONMENT=LocalDevelopment
      # Alter if not using DynamoDb
     - DynamoDb_LocalMode=true
     - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
     - AWS_REGION=eu-west-2
     - AWS_ACCESS_KEY_ID=local
     - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database

  financial-transaction-listener-test:
    image: financial-transaction-listener-test
    build:
      context: .
      dockerfile: FinancialTransactionListener.Tests/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
        - SONAR_TOKEN=${SONAR_TOKEN}
    environment:
      - ENVIRONMENT=LocalDevelopment
      # Alter if not using DynamoDb
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database
    
  # Alter if not using DynamoDb
  dynamodb-database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
      
